system:
  mode:     # debug release test
  ip:
  port:
db:
  mode:     # mysql pgsql sqlite
  db_name:
  host:
  port:
  user:
  password:
redis:
  host:
  port:
  db:
  password:
jwt:
  expires:
  issuer:
  secret:
router:
  white_router:
    - /api/captcha/generate
    - /api/email/send
    - /api/user/login
    - /api/user/register
    - /api/site/site
info:
  site:
    title:
    en_title:
    slogan:
    logo:
    icp:
  project:
    title:
    icon:
    path:
  login:
    captcha:
      enable:
      type:     # string math
    email:
      enable:
      domain:
      port:
      send_email:
      auth_code:
      send_nickname: