system:
  mode:     # debug release test
  ip:
  port:
db:
  mode:     # mysql pgsql sqlite
  db_name:
  host:
  port:
  user:
  password:
redis:
  host:
  port:
  db:
  password:
jwt:
  expires:
  issuer:
  secret:
captcha:
  enable:
  type:
email:
  enable:
  domain:
  port:
  send_email:
  auth_code:
  send_nickname: